### ISSUE TITLE
how to change txt to bin?

### ISSUE THREAD

**Issue by hmtbgc** [LijunChang/Near-Maximum-Independent-Set#1]
Thank you for your excellent project.
Problem:I want to run this script to solve my own MIS problem. 
How can I change the txt file to bin file? Can you provide a tool to do this change?(The program I write may have some bugs which cannot pass your program's first check)
Thanks!

**Comment by hmtbgc** [comment]
I solved the problem

**Comment by junyijiang** [comment]
Hello!
Problem: my terminal show that 'Can not open file: {BDOne}/b_degree.bin'.
Is this the same problem you encountered and how did you solve it？
Thanks！

**Comment by hmtbgc** [comment]
I'm sorry it has been a long time since I last checked this program.
But I suggest you can check the correctness of path and the way you read .bin flie.

**Comment by hmtbgc** [comment]
I checked the author's repository just now and found a useful [tool]. (https://github.com/LijunChang/Cohesive_subgraph_book/tree/master/datasets)
If you meet the same problem with me, I think the above tool will help.

**Comment by junyijiang** [comment]
Thanks a lot for your help！
This tool does convert txt files to bin format.
I solved the problem.
