### ISSUE TITLE
Tool error: txt file converted to bin format

### ISSUE THREAD

**Issue by junyijiang** [LijunChang/Near-Maximum-Independent-Set#4]
Hello！
I used the Tool in  https://github.com/LijunChang/Cohesive_subgraph_book/tree/master/datasets.
I did a bin format conversion of the data you provided.
However, when using the transformed data to find independent sets, the results are different. Error occurred with n and m of bin file.As shown below
![Error occurred with n and m of bin file](https://user-images.githubusercontent.com/95907157/159015678-24cb50b8-61b0-4090-9ba8-2c3bd1c53110.png)
I suspect this is the result of my mishandling. This is the command I use when using the format conversion tool, I don't know if it is correct.
![toolcommand](https://user-images.githubusercontent.com/95907157/159016161-57dcf726-81ec-4ad7-a4b9-828cafbcae48.png)
Hope to get your reply, and I sincerely thank you for answering my first question.

**Comment by LijunChang** [comment]
This is because the input to edgelist2binary is not adj.txt or degree.txt, but a file with a list of edges.

**Comment by junyijiang** [comment]
Thanks for your prompt answer!
Your timely updated example helped me a lot.
